<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE note[
			<!ELEMENT meubles (type)>
			<!ELEMENT type (ecurie)>
			<!ELEMENT design (design)>
			<!ELEMENT meuble EMPTY>
			<!ATTLIST meuble nom CDATA #REQUIRED
							description CDATA #IMPLIED>
			<!ATTLIST type type_meuble CDATA #REQUIRED>
			<!ATTLIST design design_meuble CDATA #REQUIRED> 
			]><meubles><type type_meuble = "armoire" ><design design_meuble="modern"><meuble nom="dd" description=""></meuble><meuble nom="dd" description=""></meuble></design></type><type type_meuble = "commode" ><design design_meuble="modern"><meuble nom="cznc" description="jnzbijan"></meuble></design></type></meubles>